export const seoFacts = [
  "Google processes over 3.5 billion searches per day worldwide.",
  "The first result in Google gets approximately 32% of all clicks.",
  "Long-form content typically performs better in search rankings than short content.",
  "Mobile-first indexing has been Google's default approach since 2019.",
  "93% of all online experiences begin with a search engine.",
  "The average Google first page result contains 1,447 words.",
  "Websites on HTTPS receive a small ranking boost from Google.",
  "Voice search accounts for 20% of mobile queries.",
  "Pages with videos are 53 times more likely to rank on Google's first page.",
  "Website loading speed is a crucial ranking factor for both desktop and mobile.",
  "Google's algorithm uses over 200 ranking factors to determine search results.",
  "Backlinks remain one of the top three ranking factors for Google.",
  "Featured snippets appear in about 19% of SERPs.",
  "Local SEO searches with 'near me' have grown by 150% faster than traditional local searches.",
  "Social signals, while not direct ranking factors, correlate with better search rankings.",
  "75% of users never scroll past the first page of search results.",
  "Google updates its search algorithm 500-600 times per year.",
  "Content with images gets 94% more views than content without images.",
  "The average length of meta descriptions that get displayed is 155-160 characters.",
  "Over 60% of all searches are now performed on mobile devices.",
  "Domain age is a factor in Google's ranking algorithm.",
  "Pages with blog content have 434% more indexed pages than those without.",
  "Websites with blogs have 97% more inbound links.",
  "The ideal blog post length for SEO is between 2,100 and 2,400 words.",
  "46% of all Google searches are looking for local information.",
  "Title tags that contain numbers tend to have a higher click-through rate.",
  "Updating and republishing old blog posts can increase organic traffic by 111%.",
  "61% of marketers say improving SEO is their top inbound marketing priority.",
  "SEO leads have a 14.6% close rate compared to 1.7% for outbound leads.",
  "Google prefers websites that are updated regularly with fresh content.",
];
